version: "3"
services:
  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
    - persistent:/var/lib/postgresql/data
    networks:
    - "private"
  api:
    build: ./service
    volumes:
    - "ivy-cache:/root/.ivy2/cache"
    - "docker-scala-sbt-cache:/root/.sbt"
    - "coursier-cache:/root/.cache/coursier"
    networks:
    - "private"
    ports:
    - 8007:8080
  gate:
    image: 'nginx:alpine'
    volumes:
    - "./etc/gate/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
    - "private"
    - "public"
    ports:
    - "8008:80"
  frontend:
    build: ./static
    volumes:
    - "ivy-cache:/root/.ivy2/cache"
    - "docker-scala-sbt-cache:/root/.sbt"
    - "coursier-cache:/root/.cache/coursier"
    networks:
    - "public"
    - "private"
    ports:
    - 8009:8080

networks:
  private:
  public:

volumes:
  persistent:
  ivy-cache:
  docker-scala-sbt-cache:
  coursier-cache:
