version: "3"
services:
  backend:
    image: 'nginx:alpine'
    volumes:
    - "./backend:/usr/share/nginx/html"
    networks: 
    - "private"
  serv:
    image: 'nginx:alpine'
    volumes: 
    - "./etc/serv/default.conf:/etc/nginx/conf.d/default.conf"
    networks: 
    - "private"
    ports:
    - "8000:80"
  gate:
    image: 'nginx:alpine'
    volumes: 
    - "./etc/gate/default.conf:/etc/nginx/conf.d/default.conf"
    networks: 
    - "private"
    - "public"
    ports:
    - "8008:80"
  frontend:
    image: 'nginx:alpine'
    volumes:
    - "./frontend:/usr/share/nginx/html"
    networks:
    - "public"

networks:
  private:
  public:
